---
roles:
  - name: nginxinc.nginx
    version: 0.24.3
collections:
  - name: hetzner.hcloud
    version: 4.2.1
  - name: community.crypto
    version: 2.22.2
  - name: community.general
    version: 9.5.1
  - name: ansible.posix
    version: 1.6.2
