---
- name: Ansible 101 - Example Playbook
  hosts: all
  become: true
  vars:
    username: bob
    group: builder
  tasks:
    - name: "Ensure group {{ group }} exists"
      ansible.builtin.group:
        name: "{{ group }}"
        state: present

    - name: "Ensure user {{ username }} exists"
      ansible.builtin.user:
        name: "{{ username }}"
        comment: Created using Ansible
        group: "{{ group }}"
        shell: /bin/bash
        state: present
